sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t lxin/docker-react -f Dockerfile .

script:
  - docker run -e CI=true lxin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact"
  bucket_name: "elasticbeanstalk-us-east-1-74176786631"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
